name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0
      - name: Install
        run: pnpm install
      - name: Lint
        run: pnpm run lint
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0
      - name: Install
        run: pnpm install
      - name: Lint
        run: pnpm run test
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0
      - name: Install
        run: pnpm install
      - name: Lint
        run: cd packages/components && pnpm run build
